name: bakerie_haven
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


# run `flutter pub outdated`.flutter pub upgrade --major-versions`
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  flutterfire_cli: ^0.2.2+2
  firebase_auth: ^3.3.20
  firebase_database: ^9.0.16
  firebase_storage: ^10.2.18
  path: ^1.8.1
  path_provider: ^2.0.11
  cool_nav: ^0.1.0
  geolocator: ^9.0.0
  provider: ^6.0.3
  file_picker: ^4.6.1
  google_fonts: ^3.0.1
  location: ^4.4.0
  flutter_local_notifications: ^9.6.1
  firebase_analytics: ^9.1.12
  firebase_crashlytics: ^2.8.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  #for goofd coding practise.
  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:


  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/
      - assets/google_fonts/

  fonts:
    - family: Caveat #keep creating families 
      fonts:
      - asset: assets/google_fonts/static/Caveat-Regular.ttf
        style: italic
        weight: 700