// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxBDJgW_34gtWSOgNGnDykrFzD6JuMWwM',
    appId: '1:812072198825:web:c9295da1aae75fa527ffb8',
    messagingSenderId: '812072198825',
    projectId: 'bakerie-827e6',
    authDomain: 'bakerie-827e6.firebaseapp.com',
    storageBucket: 'bakerie-827e6.appspot.com',
    measurementId: 'G-XQZPXP74E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcr1shPb6Jz1f3BHtl1KhC1Edatg8IWcs',
    appId: '1:812072198825:android:e98a19ead7df79c527ffb8',
    messagingSenderId: '812072198825',
    projectId: 'bakerie-827e6',
    storageBucket: 'bakerie-827e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5b5rgxMEMpJ1wOZY-psl13ixFQ2PmeGs',
    appId: '1:812072198825:ios:a741eb66de38915327ffb8',
    messagingSenderId: '812072198825',
    projectId: 'bakerie-827e6',
    storageBucket: 'bakerie-827e6.appspot.com',
    iosClientId:
        '812072198825-e6qhe3er75bhu5nni3nqn2ivrpk62h35.apps.googleusercontent.com',
    iosBundleId: 'com.bakerie.haven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5b5rgxMEMpJ1wOZY-psl13ixFQ2PmeGs',
    appId: '1:812072198825:ios:168254b82999271827ffb8',
    messagingSenderId: '812072198825',
    projectId: 'bakerie-827e6',
    storageBucket: 'bakerie-827e6.appspot.com',
    iosClientId:
        '812072198825-j79m1i08llt8ume1fd7gfe0bvbuq41sn.apps.googleusercontent.com',
    iosBundleId: 'com.bakerie.haven',
  );
}
